application: image-host
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets
  
- url: /i/(img|thumb).*
  script: frontend.app

- url: /.*
  script: backend.app
  login: admin

libraries:
- name: jinja2
  version: latest
